baseURL = 'https://diy.codices.one/'
languageCode = 'en-us'
title = 'diy.codices.one'
theme = 'terminal'
summaryLength = 30
publishDir = "../public"
copyright = '2026 codices.one'

[params]
  logo.logoText = "DIY.codices.one"
  centerTheme = true
  readMore = "Read more"
[menu]
  [[menu.main]]
    identifier = "woodworking"
    name = "Woodworking"
    url = "/woodworking"
  [[menu.main]]
    identifier = "cooking"
    name = "Cooking"
    url = "/cooking"
